## Blocek1, Dutch, nl, CP850/858
## This translation was created by Google AI.
## Please help the FreeDOS group to improve it.
##

#_OK
' <BARVA=!;KLAVESY=o#1;VYZNAM=!1>O<SB>K '
#_OK2
' <BARVA=!;KLAVESY=o#1#2;VYZNAM=!1>O<SB>K '
#_ANO
' <BARVA=!;KLAVESY=j#1;VYZNAM=!1>J<SB>a '
#_NE
' <BARVA=!;KLAVESY=n#2;VYZNAM=!2>N<SB>ee '
#_CANCEL
<BARVA=!;KLAVESY=a#2;VYZNAM=!3>A<SB>nnuleren
#_CANCEL2
' <BARVA=!;KLAVESY=a#2;VYZNAM=!3>A<SB>nnuleren '
#_POMOC
<BARVA=!;KLAVESY=h;VYZNAM=!4>H<SB>elp
#_PALETA
<BARVA=!;KLAVESY=p;VYZNAM=!6>P<SB>alet
#_MIXBAREV
K<BARVA=!;KLAVESY=l;VYZNAM=!7>l<SB>euren mixen
#_FS_INFO
<BARVA=!;KLAVESY=i;VYZNAM=!8>I<SB>nfo
#_FS_DISK
<BARVA=!;KLAVESY=s;VYZNAM=!9>S<SB>chijf
#_ZADAT
In<BARVA=!;KLAVESY=v;VYZNAM=!14>v<SB>oeren
#_PRIDEJPOL
<VYZNAM=!17><<---
#_UBERPOL
<VYZNAM=!18>--->>
#_FS_NOVYADRESAR
Nieu<BARVA=!;KLAVESY=w;VYZNAM=!19>w<SB>e map
#_ZPET
<BARVA=!;KLAVESY=t;VYZNAM=!20>T<SB>erug
#_VPRED
Voor<BARVA=!;KLAVESY=u;VYZNAM=!21>u<SB>it
#_FS_NAHORU
O<BARVA=!;KLAVESY=m;VYZNAM=!23>m<SB>hoog
#_FS_TRIDENI
So<BARVA=!;KLAVESY=r;VYZNAM=!24>r<SB>teren
#_INFO
'Info:            '
#_DOTAZ
'Vraag:           '
#_ANONE_DOTAZ
'Vraag:           '
#_CHYBA
Fout!
#_VLOZ_TEXT
Tekst invoegen:
#_VYBER_BARVU
Kies kleur:
#_FS_ADR_JAKSEMAJMENOVAT
Naam van de map opgeven
#_FS_PRO_CTENI
'alleen lezen, '
#_FS_SKRYTY
'verborgen, '
#_FS_SYSTEMOVY
'systeem, '
#_FS_ARCHIVOVAT
'archief, '
#_FS_ZADNE
geen.
#_FS_ZPRAVA
Bericht:
#_FS_SOUBOR
'Bestand: '
#_FS_VELIKOST
'Grootte: '
#_FS_B
' B ('
#_FS_KB
' kB)'
#_FS_B2
' bytes'
#_FS_KB2
KB
#_FS_MB2
MB
#_FS_GB2
GB
#_FS_POSL_ZMENA
'Laatst gewijzigd: '
#_FS_ATRIBUTY
'Attributen: '
#_FS_VYBER_SOUBOR
Kies bestand:
#_FS_SOUBORNEVYTVOREN
Kan bestand niet maken.
#_FS_ADRESARNEVYTVOREN
Kan map niet maken.
#_FS_DISK2
Stations:
#_FS_DISK3
'Station '
#_FS_JMENOVKADISKU
'Volumenaam:     '
#_FS_SYSTEMSOUBORU
'Bestandssysteem:'
#_FS_KAPACITA
'Capaciteit:     '
#_FS_VOLNEHO
'Vrije ruimte:   '
#_FS_SERCISLO
Serienummer:
#_FS_VYBER_NECO
Er moet een bestand geselecteerd zijn.
#_FS_JEDNOTKA_NEPRIPRAVENA
Station is niet klaar.
#_FS_TRIDENI_NADPIS
Sortering:
#_FS_TRIDENI_MIX1
naam*datum*extensie
#_FS_TRIDENI_MIX2
oplopend*aflopend
#_PREPSATSOUBOR
Bestand overschrijven?
#_VSEPOL
alle items
#_VYBPOL
geselect. items
#_ZAMPOL
geweigerde items
#_VYBINFO
In het rechterpaneel staan alle items, in het linker de geselecteerde.
Selecteren en verwijderen doe je met Enter.
Wissel tussen panelen met Tab.
#_VYBINFO2
In het linkerpaneel staan geselecteerde items, in het rechter de geweigerde.
Selecteren en verwijderen doe je met Enter.
Wissel tussen panelen met Tab.
#_MOUSE_NOT_INSTALLED
Muisstuurprogramma niet ge‹nstalleerd. Laad CTmouse of soortgelijk.
#_LFB_NOT_AVAILABLE
Uw videokaart ondersteunt de LFB-modus voor de gevraagde videomodus niet.
