## Blocek2, dutch, nl, cp850/858
## For instructions for translators please look into file TRANSLAT.TXT
## This translation was created by Google AI.
## Please help the FreeDOS group to improve it.
##

#identifikuj_se
Nederlands   (nl)
#identifikuj_se2
blocek2.nl
#sys_font
858-16.fv
#sys_font_maly
## latin214.fv
858-14.fv
#chyba_videomodu
Gewenste videomodus niet beschikbaar:
#sys_font_kodovani
858
#m1
<BARVA=!;KLAVESY=b>B<SB>estand
#m2
<BARVA=!;KLAVESY=o>O<SB>pties
#m3
<BARVA=!;KLAVESY=h>H<SB>elp
#m31
<BARVA=!;KLAVESY=o>O<SB>ver het programma
#m32
<BARVA=!;KLAVESY=l>L<SB>ees INFO.TXT  <<Alt-F1>>
#m33
<BARVA=!;KLAVESY=s>S<SB>ysteeminformatie
#m34
<BARVA=!;KLAVESY=h>H<SB>ypertekst help
#m4
<BARVA=!;KLAVESY=t>T<SB>ekst
#m11
<BARVA=!;KLAVESY=n>N<SB>ieuw    <<F1>>
#m12
<BARVA=!;KLAVESY=o>O<SB>penen <<F3>>
#m13
O<BARVA=!;KLAVESY=p>p<SB>slaan  <<F2>>
#m14
Naar <BARVA=!;KLAVESY=d>D<SB>OS shell
#m15
<BARVA=!;KLAVESY=a>A<SB>fsluiten   <<ESC>>
#m16
<BARVA=!;KLAVESY=s>S<SB>luiten  <<Alt-F3>>
#m21
<BARVA=!;KLAVESY=k>K<SB>leuren
#m211
<BARVA=!;KLAVESY=v>V<SB>oorgrondkleur
#m212
<BARVA=!;KLAVESY=a>A<SB>chtergrondkleur
#m213
<BARVA=!;KLAVESY=b>B<SB>asiskleur
#m215
Kleur voor <BARVA=!;KLAVESY=m>m<SB>arkeren regel
#m22
<BARVA=!;KLAVESY=t>T<SB>aal
#m23
<BARVA=!;KLAVESY=m>M<SB>arkeer act. regel
#m24
<BARVA=!;KLAVESY=l>L<SB>ettertype
#m25
<BARVA=!;KLAVESY=a>A<SB>fbeeldingsfilter
#m26
To<BARVA=!;KLAVESY=e>e<SB>tsenborden
#m27
<BARVA=!;KLAVESY=z>Z<SB>ijpaneel
#m28
O<BARVA=!;KLAVESY=p>p<SB>slaan configuratie
#m29
<BARVA=!;KLAVESY=s>S<SB>paties markeren
#m41
Naar <BARVA=!;KLAVESY=u>U<SB>TF-8
#m42
<BARVA=!;KLAVESY=v>V<SB>an UTF-8
#m43
<BARVA=!;KLAVESY=t>T<SB>ekstterugloop
#m431
<BARVA=!;KLAVESY=f>F<SB>ixeer tekstterugloop
#m432
<BARVA=!;KLAVESY=s>S<SB>amenvoegen regels
#m44
<BARVA=!;KLAVESY=z>Z<SB>oeken      <<Ctrl-F>>
#m45
Zoek v<BARVA=!;KLAVESY=o>o<SB>lgende <<Ctrl-S>>
#m46
V<BARVA=!;KLAVESY=e>e<SB>rvangen      <<Ctrl-H>>
#m460
<BARVA=!;KLAVESY=b>B<SB>ladwijzers
#m47
<BARVA=!;KLAVESY=k>K<SB>arakterkaart
#m48
<BARVA=!;KLAVESY=c>C<SB>onversies <<CTRL-K>>
#m49
B<BARVA=!;KLAVESY=l>l<SB>okbewerkingen
#m490
<BARVA=!;KLAVESY=q>Q<SB>R-code genereren
#m491
Naar <BARVA=!;KLAVESY=h>H<SB>TML-entiteiten
#m492
Naar h<BARVA=!;KLAVESY=o>o<SB>ofdletters
#m493
Naar <BARVA=!;KLAVESY=k>k<SB>leine letters
#m494
<BARVA=!;KLAVESY=v>V<SB>an HTML-entiteiten
#m495
B<BARVA=!;KLAVESY=a>a<SB>rcodes
#vyber_soubor
Selecteer bestand:
#jak_to_ulozit
Hoe moet ik dit opslaan?
#soubor_existuje_prepsat
Dit bestand bestaat al
overschrijven?
#o_programu
over
#napoveda
help
#varovani
<BARVA=51200>waarschuwing!<SB>
#opravdu_konec
Echt afsluiten?
Niet-opgeslagen wijzigingen gaan verloren.
#tento_soubor_uz_jednou_mame
Dit bestand is al geopend.
Blocek staat toe het opnieuw te openen,
maar het zal onafhankelijk van de eerste instantie werken!
d.w.z.
NIET ZOALS DE PASCAL IDE
#unicode
unicode
#zalamovani
tekstterugloop
#proporcionalni_mod
proportioneel
#vyber_barvu_popredi
Selecteer voorgrondkleur
#vyber_barvu_pozadi
Selecteer achtergrondkleur
#vyber_barvu_zakladu
Selecteer basiskleur
#vyber_barvu_prosv
Kies een kleur
#zda_pro_rad
Actuele regel markeren?
#nastaveni_ulozeno
Instellingen opgeslagen

#zatim_neni
Deze functie is nog niet beschikbaar.

#hypertextova_napoveda
Hypertekst help

#napoveda_koren
Blocek - teksteditor en afbeeldingsviewer

Helponderwerpen:
1) <OK="napoveda_klavesy">Bediening<OK/>
2) <OK="napoveda_mys">Bediening met muis<OK/>
3) <OK="napoveda_prvky">Interface-elementen<OK/>

#napoveda_klavesy
<FONT=surea37.fn;barva=65346>Bediening<SB;SF>
<barva=65535>F10<sb>   - open hoofdmenu
<barva=65535>F1<sb>    - maak nieuw bestand
<barva=65535>F2<sb>    - sla bestand op
<barva=65535>F3<sb>    - open bestand
<barva=65535>Alt+F3<sb> - sluit bestand
<barva=65535>Alt+F1<sb> - open INFO.TXT
<barva=65535>Ctrl+F<sb> - zoeken
<barva=65535>Ctrl+S<sb> - doorgaan met zoeken
<barva=65535>Ctrl+H<sb> - zoeken en vervangen
<barva=65535>Ctrl+A<sb> - selecteer het hele document
<barva=65535>Ctrl+Q<sb> - biedt verwant karakter voor laatst getypte [a, ,...]
<barva=65535>Ctrl+K<sb> - functies voor karakterconversie
<barva=65535>Ctrl+L<sb> - snelmenu voor regelbewerking
<BARVA=65535>LShift+Alt<sb> - verander toetsenbordinstellingen
<barva=65535>Ctrl+Alt+omhoog<sb>  - selecteer de huidige regel
<barva=65535>Ctrl+Alt+omlaag<sb>   - selecteer het woord onder de cursor
<barva=65535>Ctrl+Alt+links<sb>  - selecteer alle karakters links van de cursor
<barva=65535>Ctrl+Alt+rechts<sb> - selecteer alle karakters rechts van de cursor
<barva=65535>Backspace<sb> - verwijder karakter links van de cursor
<barva=65535>Delete<sb> - verwijder karakter rechts van de cursor
<barva=65535>Shift+Delete<sb> - verwijder geselecteerd blok
<barva=65535>*pijltjes<sb> - verplaats cursor
<barva=65535>*Ctrl+PageUp<sb> of <barva=65535>*Ctrl+Home<sb> - ga naar de eerste regel van het document
<barva=65535>*Ctrl+PageDown<sb> of <barva=65535>*Ctrl+End<sb> - ga naar de laatste regel van het document
<barva=65535>*Ctrl+rechts<sb> - verplaats een woord naar rechts
<barva=65535>*Ctrl+links<sb> - verplaats een woord naar links
   Toetsen of combinaties gemarkeerd met "*" kunnen
   worden gecombineerd met <barva=65535><Shift><sb>.
In dat geval wordt de grootte van het tekstblok aangepast
   samen met de verplaatsing van de cursor.
<barva=65535>Ctrl+[1-7]<sb> - kopieer blok naar klembord 1-7
<barva=65535>Alt+[1-7]<sb> - plak tekst van klembord 1-7 op huidige positie
<barva=65535>Ctrl+plus<sb> en <barva=65535>Ctrl+minus<sb> (op numeriek toetsenbord) - snel bladeren door geopende bestanden
<barva=65535>ESC<sb>   - afsluiten
<barva=65535>Alt+F2<sb> - sla huidig scherm op

#napoveda_mys
<FONT=surea37.fn;barva=65346>Bediening met muis<SB;SF>
<barva=65535>1) In het documentvenster<SB>
Linksklik (LM) - verplaatst cursor naar die positie in het document.
LM+shift - specificeert begin en einde van een tekstblok
LM ingedrukt houden en slepen - interactieve selectie van tekstblok
Rechtsklik (RM) - toont info over het karakter en opent conversiedialoog.
Biedt ook functies voor bladwijzers.

<barva=65535>2) In de tabbalk van geopende bestanden<SB>
Klik LM - brengt het bestand naar het hoofdvenster
Klik RM - actiemenu voor dat bestand
(sluiten, alle andere sluiten, toon volledig pad)

<barva=65535>3) In de klembordindicator<SB>
Klik LM - bewerkingen voor de inhoud van het klembord

<barva=65535>4) Overige opmerkingen<SB>
->> Alle andere interface-elementen gebruiken alleen de linkermuisknop
->> Bijna alle dialoogvensters kunnen worden verplaatst door de titelbalk te slepen.
->> Door in informatievensters te slepen, kunt u tekst selecteren en
    naar het klembord kopi‰ren met <OK="napoveda_klavesy">CTRL+[1-7]<OK/>.

#napoveda_prvky
<FONT=surea37.fn;barva=65346>Interface-elementen<SB;SF>
Het grootste deel van de interface is het <barva=65535>hoofdvenster<SB>. Hierin wordt een document
of de afbeeldingsviewer getoond.
Aan de linkerkant van het document kan een zijpaneel staan
dat aangeeft hoe regels worden afgebroken.
Boven het venster bevinden zich drie panelen.

<barva=65535>1) Vaste balk<SB>
Hoofdmenu: <barva=65535>Bestand<SB>, <barva=65535>Tekst<SB>, <barva=65535>Opties<SB>, <barva=65535>Help<SB>
Aan de rechterkant bevinden zich <OK="napoveda_indikatory">klembordindicatoren<OK/> genummerd 1-7.
Helemaal rechts (rechtsboven) is een keuzemenu voor toetsenbordindelingen.
Deze lijst kan ook worden geopend met <OK="napoveda_klavesy">ALT+SHIFT<OK/>

<barva=65535>2) Contextbalk<SB>
Verandert afhankelijk van de inhoud van het hoofdvenster.
Bij een afbeelding toont het links de afmetingen in pixels.
Rechts staan knoppen voor volledig scherm, optimale weergave en rotazione/spiegelen.
Bij een document is er een knop voor karakterconversies
(ook via <OK="napoveda_klavesy">CTRL+K<OK/>). Rechts daarvan is een knop
om tekstterugloop-modi te wijzigen.
Daarnaast is een selectievakje om de tekstterugloop in of uit te schakelen.
Helemaal rechts worden de huidige kolom en regel getoond.

<barva=65535>3) Tabbladen van geopende bestanden<SB>
Zolang er geen bestand is geladen, is de onderste balk leeg.
Zodra u een bestand opent, verschijnt het tabblad in deze balk.
In Blocek kunt u veel bestanden tegelijk open hebben.
De tabbladen staan naast elkaar en u kunt ertussen wisselen met de <OK="napoveda_mys">muis<OK/>.
De linkermuisknop schakelt het hoofdvenster naar dat bestand.
De rechtermuisknop opent een submenu om het bestand te sluiten, anderen te sluiten of het pad te tonen.

#napoveda_indikatory
Als u tekst naar het klembord kopieert (<OK="napoveda_klavesy">CTRL+[1-7]<OK/>) of via een dialoog,
brandt de indicator als een gloeilamp.
Als het klembord leeg is, wordt het getoond als een doorstreepte cirkel.
Indicator nr. 7 kan verschijnen als <BARVA=65535>7W<SB>.
Dit betekent dat MS Windows klemborddiensten beschikbaar zijn.
In dit geval is klembord 7 gekoppeld aan Windows om tekst met andere programma's uit te wisselen.
Details in het bestand TECHNOTE.TXT

#text_napovedy
<FONT=surea37.fn>Blocek<SF>
versie 1.77b
compilatiedatum: <BARVA=65535>28.9.2026<SB>
Laaca (laaca@seznam.cz)

Blocek is een teksteditor en afbeeldingsviewer
die overweg kan met UTF-8 bestanden,
ideaal voor het maken van webpagina's.
Blocek kan zeer grote bestanden en lange regels
aan. Dank aan Mateusz Viste voor de Unicode-lettertypen.
Blocek werkt ook als viewer voor gangbare afbeeldingsformaten,
maar kan ze niet bewerken.
Dit programma mag worden gedistribueerd onder de GNU/GPL licentie

#parametr_otaznik
Syntaxis:
BLOCEK [bestand1 [, bestand2 [,...]]]
#ovladani_obrazku
volledig scherm*o<<>>O*+90*-90*horiz*vert*Exif-gegevens

#soubor_nebyl_ulozen
Bestand niet opgeslagen!
weinig ruimte op het station of
het station is alleen-lezen

#chyba_font_int
Fout bij het laden van het lettertypebestand
#chyba_font_neint
Ontbrekend lettertypebestand of fout bij het laden van het bestand:

#informace_exif
Informatie uit Exif-blok
#exif_date_strs
Datum en tijd:*Oorspronkelijke datum:*Digitalisatiedatum:
#exif_camera_info
Camerafabrikant:*Cameramodel:*Beschrijving:*Software:*Lichtbron:*Flitser:*Belichtingsmodus:*ISO:*Belichtingstijd:*Ori‰ntatie:*Zoom:
#exif_lightsrc_info
Onbekend*Daglicht*TL-licht*Tungsten*Flitser*Standaardlicht A*Standaardlicht B*Standaardlicht C*D55*D65*D75*Andere bron*Onbekend
#exif_flash_info
Geen flitser*Flitser*Flitser zonder voorflits*Flitser met voorflits*Auto flitser*Geen flitser*Onbekend
#exif_expos_mode
Onbekend*Handmatig*Normaal programma*Diafragmaprioriteit*Sluiterprioriteit*Creatief programma*Actiemodus*Portretmodus*Landschapsmodus*Onbekend
#exif_orientation_desc
Normaal*Horiz. spiegelen*180ø gedraaid*Vert. spiegelen*90ø links en gespiegeld*90ø rechts gedraaid*90ø rechts en gespiegeld*90ø links gedraaid*Onbekend
#exif_zoom_unused
Niet in gebruik
#exif_GPS_info
GPS-locatiegegevens*breedtegraad:*lengtegraad:*hoogte:*azimut*N*Z*W*O*m*o*'*''
#zkopirovat_exif
Naar klembord
#nejde_o_obrazek
Bestand is beschadigd of
beeldgegevens zijn niet in een ondersteund formaat
Bestand wordt geopend als tekst.
#nelze_fixovat_zalamani
Deze functie is alleen beschikbaar
in de tekstterugloopmodus.
#vyhledavani
Zoeken
#rezim_vyhled
<POZADI=1147;BARVA=65535>zoekmodus<POZADI=->
#vyhled_mozn
voor<BARVA=!;KLAVESY=u>u<SB>it
acht<BARVA=!;KLAVESY=e>e<SB>ruit
van <BARVA=!;KLAVESY=b>b<SB>egin
#roz_vel_pismen
<BARVA=!;KLAVESY=h>H<SB>oofdlettergevoelig

#text_nenalezen
Opgegeven tekst is niet gevonden.
#nahradit_vyskyt
Deze markering vervangen?
#potvrzovat
be<BARVA=!;KLAVESY=v>v<SB>estigen
#nahradvse
vervan<BARVA=!;KLAVESY=g>g<SB> alles
#hledany_text
zoektekst:
#novy_text
nieuwe tekst
#nahrada_textu
tekst vervangen
#vyber_filtr
Selecteer filter
#opravdu_zavrit
Bestand is gewijzigd.
Opslaan?
#zavrit_ostatni
Sluit alle andere
#umisteni_souboru
Bestandslocatie
#bezejmenny
<BARVA=46815><<nieuw>><SB>
#bezejmenny_soubor
Nieuw bestand

#zrusit_nac
Laden afbreken?
#chybi_bcfg
Configuratiebestand <BARVA=65535>BLOCEK.CFG<SB>
bestaat nog niet.
Ik zal het aanmaken door
<BARVA=65535>DEFAULT.CFG<SB> te kopi‰ren.
#chybny_bcfg
Configuratiebestand <BARVA=65535>BLOCEK.CFG<SB>
heeft een onjuist formaat.
Daarom overschrijf ik het met
<BARVA=65535>DEFAULT.CFG<SB>
#pridani_bcfg
Aan configuratiebestand <BARVA=65535>BLOCEK.CFG<SB>
zijn deze items uit <BARVA=65535>DEFAULT.CFG<SB> toegevoegd:
#pocet_zmen
Gevonden*Aantal wijzigingen:*Aantal weergaven*<BARVA=!;KLAVESY=f>F<SB>unctie voor aantal weergaven
#neniswap
Uw systeem ondersteunt geen virtueel geheugen!
Dit kan gevaarlijk zijn (geheugentekort).
Probeer een andere DPMI-manager.
momenteel ge‹nstalleerd:
#dpmineznamy
<BARVA=333>onbekende DPMI-manager :-(<SB>
#kaslinaswap
(U kunt deze controle uitschakelen door
<BARVA=65530>zkontroluj_swap = 0<SB> in BLOCEK.CFG in te stellen)
#plnyseznam
Volledige lijst...
#vybprefkl
Welke toetsenborden moeten in het basismenu staan?
#vybprefflt
Welke filters moeten in het basismenu staan?

#asciiauto
autodetectie

#vkod
<PODTRH=+>bron<PODTRH=->
#ckod
<PODTRH=+>doel<PODTRH=->
#oznaceno
geselecteerd:
#ozn_nic
niets
#kompinfo
Processor:*Geheugen:*MB RAM*Video:* VESA versie:*Videomodus:*Videogeheugen*Vernieuwingsfreq.:*BIOS default*DOS-versie:*Karakterset:*DOS landcode:*OS
#videomody
<BARVA=!;KLAVESY=v>V<SB>ideomodi*Overzicht modi
#kompinfo_lfn
Lange bestandsnamen (LFN):
#schranka_c
Klembord nr.
#schranka_do
Naar klembord kopi‰ren
#schranka_ze
Van klembord plakken
#schranka_copy
Kopieer naar een ander klembord
#schranka_smaz
Wissen
#vyber_jazyk
Selecteer taal
#nutny_restart
Herstart vereist om taal te wijzigen.
#prevod_html_entity
Converteer naar HTML-entiteiten
#prevod_html_ent_info
Karakters met ASCII/Unicode-waarde boven 127
worden omgezet naar HTML-entiteiten.
Het bereik hangt af van het geselecteerde blok.
#text_je_v_unicode
Tekst is in Unicode.
#text_je_v_ascii
Tekst is in ASCII-codering en wordt
geconverteerd volgens de conversietabel.
#neni_oz_blok
Geen blok geselecteerd - ik converteer
de hele tekst
#prevod_mala_velka
Tekst naar hoofdletters
#prevod_mala_velka_inf
Verandert kleine letters in het blok naar hoofdletters.
Andere karakters blijven ongewijzigd.
#prevod_velka_mala
Tekst naar kleine letters
#prevod_velka_mala_inf
Verandert hoofdletters in het blok naar kleine letters.
Andere karakters blijven ongewijzigd.
#kodovani_dokumentu
codering:
#help_non_unicode
Verandert alleen de karakterset-label. Het lettertype verandert niet.
#help_inter_znaku
Conversies tussen karakters en sequenties in UTF-8 of UTF-16.
Sommige subfuncties gelden voor een blok, andere voor het hele document.
Overschakelen tussen Unicode/non-Unicode verandert het lettertype.
#help_tabkonv_znaku
Zet karakters via tabellen om naar een andere codering.
Aantal karakters blijft gelijk.
Geldt voor geselecteerd blok of hele tekst.
Overschakelen tussen Unicode/non-Unicode verandert het lettertype.

#analyza_nedef_zn_dok
Analyse van ongedefinieerde karakters (document)

#analyza_nedef_zn_blok
Analyse van ongedefinieerde karakters (blok)

#poc_vysk_nedef_znaku_n
aantal keer weergegeven

#poc_vysk_nedef_znaku_vse
totaal ongedefinieerde karakters

#poc_vysk_nedef_znaku_unik
unieke ongedefinieerde karakters:*hun bereik:

#zamena_znaku
Karakter vervangen?
#nedefinovany_znak
Ongedefinieerd karakter*Analyse ongedef. karakters

#nedefinovany_znak_zam
Alle ongedefinieerde karakters vervangen?

#zamena_znaku_radiob1
Eenmalige vervanging
In het hele document
In geselecteerd blok

#zamena_znaku_radiob2
overal
vanaf het begin tot aan karakter
vanaf karakter en verder

#znak_k_zamene
Vervangend karakter...

#dotaz_pri_zmene
Vragen voor wijziging?
#kodovaniascii_dlg
Waarschijnlijke ASCII-codering:*kan niet bepalen*Akkoord?

#polozka_dos
(met tabel)*(zonder tabel)*meer...

#tbl_filtr_ascii
Conversie in groep:*broncodering*doelcodering

#niz_nonunicode1
In welke codering is de tekst weergegeven?

#niz_nonunicode2
Bron- en doelcodering zijn identiek.
Er worden geen wijzigingen aangebracht.

#ascii_2_utf_1
Conversies tussen ASCII en UTF-8/UTF-16 sequenties

#ascii_2_utf_2
Blokbewerkingen (verandert algemene codering niet)

#ascii_2_utf_3
Gehele document bewerkingen (schakelt over naar Unicode)

#uni_2_utf_1
Conversies tussen Unicode en UTF-8/UTF-16 sequenties

#uni_2_utf_2
Blokbewerkingen (verandert algemene codering niet)

#uni_2_utf_3
Gehele document bewerkingen (schakelt over naar non-Unicode [DOS])

#uni_2_utf_4
Unicode --> UTF-8 (in DOS-codering)

#prohozeni_endianity
Endianness omwisselen Unicode

#tab_konv_zn
Voert geen conversies uit.
Labelt document alleen als non-Unicode.
Karakters 0-255 veranderen niet, hogere worden vervangen.
#zda_prenastavit_font1
Moet ik het lettertype resetten en als non-Unicode labelen?

#zda_prenastavit_font2
Moet ik het lettertype resetten en als Unicode labelen?
#pren_font_ano
(hele tekst wordt geconverteerd, JA aanbevolen)

#pren_font_ne
(deel wordt geconverteerd, NEE aanbevolen)

#preznacit_kodovani
Moet ik de codering van het document relabelen?
#zm_kod_dok
Wijziging documentcodering

#zak_unicode
Document is gecodeerd in de Unicode-standaard.

#sada_a_filtr_souborem
Karakterset en filter worden bepaald door bestand:

#interp_nonuni
Interpretatie non-Unicode

#konv_zn_utf
Conversie sequentie karakter/UTF

#tab_konv_zz
Tabelconversie karakter/karakter

#zmena_fontu
Lettertype wijzigen

#nas_zal_rad
Instellingen tekstterugloop

#nas_zal_mozn
volgens venster
78 karakters
80 karakters
aangepast...

#filesel_nejde_konverze
De naam kan niet correct worden geconverteerd
naar de huidige DOS-codepage.
Toch doorgaan?

#podrobnosti
Details

#moznosti...
Opties...

#form_konc_rad
Formaat regeleinde

#form_konc_help
Aanbevolen wordt de CRLF-standaard (DOS/Windows).
LF is de Unix/Linux-standaard en
CR werd gebruikt op Macintosh-computers.
#form_konc_mozn
CRLF (DOS/win)
LF (Unix)
CR (Mac)

#b_ord_mark
Byte order mark (BOM)

#bom_help
"BOM" = byte order mark
Geldt alleen voor Unicode-bestanden.
Het is een reeks van drie bytes
aan het begin van het bestand.
Aanbevolen voor UTF-16 bestanden.
Wordt normaal niet gebruikt voor UTF-8.

#bom_mozn
UTF-8
UTF-16le
UTF-16be

#opravdu_fix_lom
Wilt u echt de tekstterugloop in de hele tekst fixeren?
#rozs_fix_lom_blok
Blok kruist geen enkel regeleinde
Uitbreiden en doorgaan?

#jen_nezalam_rezim
Deze functie is alleen beschikbaar zonder tekstterugloop.
#opravdu_spoj_radky
Echt de regels in alinea's over de hele tekst samenvoegen?

#nahr_faze
1e fase:*2e fase:*3e fase:

#jen_v_bloku
A<BARVA=!;KLAVESY=l>l<SB>leen in blok

#prevod_z_html_entit
Decodeer HTML-entiteiten naar karakters

#prevod_z_html_entit_info
Herkent HTML-entiteiten (bijv. &#8222;) en vervangt ze door Unicode-karakters

#qr_vygenerovany
QR-code gegenereerd

#qr_ulozit
Opslaan

#qr_velikost
Puntgrootte in QR-code (1-20)

#qr_uspech
Succes! Opgeslagen als:

#qr_chyba
Fout tijdens conversie naar QR-code.

#qr_chyba_save
Fout bij opslaan QR-code.
#qr_tvorba
Creatie van QR-codes

#qr_text
Tekst om te converteren naar QR-code

#related_characters
Gerelateerde karakters

#zalozky
Bladwijzers*Bladwijzer nr.*Toon bladwijzers

#menu_slovo
menu/woord

#dialogy_menu_slovo
Dialoog Zoeken*Dialoog Vervangen*HOOFDLETTERS*kleine letters*Eerste Hoofdl.*Naar klembord

#menu_radek
menu/regel

#dialogy_menu_radek1
Regel naar blok:
m<BARVA=!;KLAVESY=e>e<SB>t terugloop
zon<BARVA=!;KLAVESY=d>d<SB>er terugloop

#dialogy_menu_radek2
Spaties:
verwijder spaties aan <BARVA=!;KLAVESY=b>b<SB>egin
verwijder spaties aan e<BARVA=!;KLAVESY=i>i<SB>nd

#dialogy_menu_radek3
Inspringen:
volgens regel bo<BARVA=!;KLAVESY=v>v<SB>en
volgens <BARVA=!;KLAVESY=t>t<SB>abulatie

#pmysmenu
<BARVA=!;KLAVESY=k>k<SB>arakter
w<BARVA=!;KLAVESY=o>o<SB>ord
<BARVA=!;KLAVESY=r>r<SB>egel

#doprad
Regel aanvullen

#doprad_txt
Typ een of meer karakters om de
ruimte te vullen van het einde
van de regel tot waar u klikte.
Standaard is [spatie]

#zarovnani
Uitlijning:*links*rechts

#carkod_tvorba
Barcodes

#carkod_instr
Voer een nummer of korte tekst in
Let op: Sommige barcodeformaten ondersteunen alleen nummers.
Bovendien vereisen sommige (bijv. EAN-13)
geldige codes met de juiste checksum.
Ongeldige nummers kunnen worden gecodeerd, maar
lezers kunnen deze mogelijk niet verwerken.

#carkod_ulozit
Opslaan

#carkod_uspech
Succes! Opgeslagen als:

#carkod_chyba
Fout tijdens conversie naar barcode.

#carkod_chyba_save
Fout bij opslaan barcode.
#carkod_combine
Voeg gecodeerde string toe

#carkod_mozn
Deze string kan worden gecodeerd in de volgende barcodes:
