## Blocek1, Slovenian, sl, CP852
## This translation was created by Google AI.
## Please help the FreeDOS group to improve it.
##

#_OK
' <BARVA=!;KLAVESY=o#1;VYZNAM=!1>O<SB>K '
#_OK2
' <BARVA=!;KLAVESY=o#1#2;VYZNAM=!1>O<SB>K '
#_ANO
' <BARVA=!;KLAVESY=d#1;VYZNAM=!1>D<SB>a '
#_NE
' <BARVA=!;KLAVESY=n#2;VYZNAM=!2>N<SB>e '
#_CANCEL
Prekli<BARVA=!;KLAVESY=c#2;VYZNAM=!3>c<SB>i
#_CANCEL2
' Prekli<BARVA=!;KLAVESY=c#2;VYZNAM=!3>c<SB>i '
#_POMOC
Po<BARVA=!;KLAVESY=m;VYZNAM=!4>m<SB>oü
#_PALETA
<BARVA=!;KLAVESY=p;VYZNAM=!6>P<SB>aleta
#_MIXBAREV
MeÁanje <BARVA=!;KLAVESY=b;VYZNAM=!7>b<SB>arv
#_FS_INFO
<BARVA=!;KLAVESY=i;VYZNAM=!8>I<SB>nfo
#_FS_DISK
Dis<BARVA=!;KLAVESY=k;VYZNAM=!9>k<SB>
#_ZADAT
<BARVA=!;KLAVESY=v;VYZNAM=!14>V<SB>nesi
#_PRIDEJPOL
<VYZNAM=!17><<---
#_UBERPOL
<VYZNAM=!18>--->>
#_FS_NOVYADRESAR
Nov<BARVA=!;KLAVESY=a;VYZNAM=!19>a<SB> mapa
#_ZPET
Na<BARVA=!;KLAVESY=z;VYZNAM=!20>z<SB>aj
#_VPRED
Napre<BARVA=!;KLAVESY=j;VYZNAM=!21>j<SB>
#_FS_NAHORU
<BARVA=!;KLAVESY=g;VYZNAM=!23>G<SB>or
#_FS_TRIDENI
<BARVA=!;KLAVESY=r;VYZNAM=!24>R<SB>azvrsti
#_INFO
'Info:            '
#_DOTAZ
'VpraÁanje:       '
#_ANONE_DOTAZ
'VpraÁanje:       '
#_CHYBA
Napaka!
#_VLOZ_TEXT
Vstavi besedilo:
#_VYBER_BARVU
Izberi barvo:
#_FS_ADR_JAKSEMAJMENOVAT
Vnesi ime mape
#_FS_PRO_CTENI
'samo za branje, '
#_FS_SKRYTY
'skrito, '
#_FS_SYSTEMOVY
'sistemsko, '
#_FS_ARCHIVOVAT
'arhiv, '
#_FS_ZADNE
nobena.
#_FS_ZPRAVA
Sporoüilo:
#_FS_SOUBOR
'Datoteka: '
#_FS_VELIKOST
'Velikost: '
#_FS_B
' B ('
#_FS_KB
' kB)'
#_FS_B2
' bajtov'
#_FS_KB2
KB
#_FS_MB2
MB
#_FS_GB2
GB
#_FS_POSL_ZMENA
'Spremenjeno: '
#_FS_ATRIBUTY
'Atributi: '
#_FS_VYBER_SOUBOR
Izberi datoteko:
#_FS_SOUBORNEVYTVOREN
Datoteke ni bilo mogoüe ustvariti.
#_FS_ADRESARNEVYTVOREN
Mape ni bilo mogoüe ustvariti.
#_FS_DISK2
Pogoni:
#_FS_DISK3
'Pogon '
#_FS_JMENOVKADISKU
'Oznaka pogona:  '
#_FS_SYSTEMSOUBORU
'Datoteüni sist.:'
#_FS_KAPACITA
'Zmogljivost:    '
#_FS_VOLNEHO
'Prost prostor:  '
#_FS_SERCISLO
Serijska Átevilka:
#_FS_VYBER_NECO
Izbrati morate datoteko.
#_FS_JEDNOTKA_NEPRIPRAVENA
Pogon ni pripravljen.
#_FS_TRIDENI_NADPIS
RazvrÁüanje:
#_FS_TRIDENI_MIX1
ime*datum*konünica
#_FS_TRIDENI_MIX2
naraÁüajoüe*padajoüe
#_PREPSATSOUBOR
PrepiÁi datoteko?
#_VSEPOL
vsi elementi
#_VYBPOL
izbrani elem.
#_ZAMPOL
zavrnjeni elem.
#_VYBINFO
V desnem podoknu so vsi elementi, v levem pa izbrani.
Izbiranje in brisanje poteka s tipko Enter.
Med podokni preklapljate s tipko Tab.
#_VYBINFO2
V levem podoknu so izbrani elementi, v desnem pa zavrnjeni.
Izbiranje in brisanje poteka s tipko Enter.
Med podokni preklapljate s tipko Tab.
#_MOUSE_NOT_INSTALLED
Gonilnik za miÁko ni nameÁüen. Naloßite CTmouse ali podobno.
#_LFB_NOT_AVAILABLE
VaÁa grafiüna kartica ne podpira naüina LFB za zahtevani video naüin.
