## Blocek1, Swedish, sv, CP850
## This translation was created by Google AI.
## Please help the FreeDOS group to improve it.
##

#_OK
' <BARVA=!;KLAVESY=o#1;VYZNAM=!1>O<SB>K '
#_OK2
' <BARVA=!;KLAVESY=o#1#2;VYZNAM=!1>O<SB>K '
#_ANO
' <BARVA=!;KLAVESY=j#1;VYZNAM=!1>J<SB>a '
#_NE
' <BARVA=!;KLAVESY=n#2;VYZNAM=!2>N<SB>ej '
#_CANCEL
<BARVA=!;KLAVESY=a#2;VYZNAM=!3>A<SB>vbryt
#_CANCEL2
' <BARVA=!;KLAVESY=a#2;VYZNAM=!3>A<SB>vbryt '
#_POMOC
<BARVA=!;KLAVESY=h;VYZNAM=!4>H<SB>j„lp
#_PALETA
<BARVA=!;KLAVESY=p;VYZNAM=!6>P<SB>alett
#_MIXBAREV
<BARVA=!;KLAVESY=b;VYZNAM=!7>B<SB>landa f„rger
#_FS_INFO
<BARVA=!;KLAVESY=i;VYZNAM=!8>I<SB>nfo
#_FS_DISK
<BARVA=!;KLAVESY=d;VYZNAM=!9>D<SB>isk
#_ZADAT
Ang<BARVA=!;KLAVESY=e;VYZNAM=!14>e<SB>
#_PRIDEJPOL
<VYZNAM=!17><<---
#_UBERPOL
<VYZNAM=!18>--->>
#_FS_NOVYADRESAR
Ny <BARVA=!;KLAVESY=k;VYZNAM=!19>k<SB>at.
#_ZPET
<BARVA=!;KLAVESY=t;VYZNAM=!20>T<SB>illbaka
#_VPRED
<BARVA=!;KLAVESY=f;VYZNAM=!21>F<SB>ram†t
#_FS_NAHORU
<BARVA=!;KLAVESY=u;VYZNAM=!23>U<SB>pp
#_FS_TRIDENI
<BARVA=!;KLAVESY=s;VYZNAM=!24>S<SB>ortera
#_INFO
'Info:            '
#_DOTAZ
'Fr†ga:           '
#_ANONE_DOTAZ
'Fr†ga:           '
#_CHYBA
Fel!
#_VLOZ_TEXT
Infoga text:
#_VYBER_BARVU
V„lj f„rg:
#_FS_ADR_JAKSEMAJMENOVAT
Ange katalognamn
#_FS_PRO_CTENI
'skrivskyddad, '
#_FS_SKRYTY
'dold, '
#_FS_SYSTEMOVY
'system, '
#_FS_ARCHIVOVAT
'arkiv, '
#_FS_ZADNE
inga.
#_FS_ZPRAVA
Meddelande:
#_FS_SOUBOR
'Fil: '
#_FS_VELIKOST
'Storlek: '
#_FS_B
' B ('
#_FS_KB
' kB)'
#_FS_B2
' byte'
#_FS_KB2
KB
#_FS_MB2
MB
#_FS_GB2
GB
#_FS_POSL_ZMENA
'Žndrad: '
#_FS_ATRIBUTY
'Attribut: '
#_FS_VYBER_SOUBOR
V„lj fil:
#_FS_SOUBORNEVYTVOREN
Kunde inte skapa fil.
#_FS_ADRESARNEVYTVOREN
Kunde inte skapa katalog.
#_FS_DISK2
Enheter:
#_FS_DISK3
'Enhet '
#_FS_JMENOVKADISKU
'Volymetikett:   '
#_FS_SYSTEMSOUBORU
'Filsystem:      '
#_FS_KAPACITA
'Kapacitet:      '
#_FS_VOLNEHO
'Ledigt utrymme: '
#_FS_SERCISLO
Serienummer:
#_FS_VYBER_NECO
En fil m†ste v„ljas.
#_FS_JEDNOTKA_NEPRIPRAVENA
Enheten „r inte redo.
#_FS_TRIDENI_NADPIS
Sortering:
#_FS_TRIDENI_MIX1
namn*datum*fil„ndelse
#_FS_TRIDENI_MIX2
stigande*fallande
#_PREPSATSOUBOR
Skriv ”ver fil?
#_VSEPOL
alla objekt
#_VYBPOL
valda objekt
#_ZAMPOL
avvisade objekt
#_VYBINFO
I den h”gra panelen finns alla objekt och i den v„nstra de valda.
Val och radering g”rs med Enter.
V„xla mellan paneler med Tab.
#_VYBINFO2
I den v„nstra panelen visas valda objekt och i den h”gra de avvisade.
Val och radering g”rs med Enter.
V„xla mellan paneler med Tab.
#_MOUSE_NOT_INSTALLED
Musdrivrutin inte installerad. Ladda CTmouse eller liknande.
#_LFB_NOT_AVAILABLE
Ditt grafikkort st”der inte LFB-l„ge f”r det beg„rda videol„get.
