# Language: Polish (MAZOVIA)
# Translated by Mateusz Viste
# Polish letters encoded in the MAZOVIA standard
#### Poland, Country=048, Codepage 790/991, EGA10.CPX
#### Country=048 gives an error message in combination
#### with Codepage 790/991 (!)
#### This file is part of the FreeDOS HTML Help Viewer
#### and is licensed under its terms.
#
# Program Usage Screen Strings
# Program Usage Screen Strings
1.0:Przegl•darka plik¢w pomocy w systemie HTML dla FreeDOS
1.1:Opcje podstawowe
1.2:Wyòwietla pomoc na ten temat
1.3:Wyòwietla ten komunikat pomocy
1.4:Wymusza tryb czarno-biaày
1.5:Uæywa fantazyjnego schematu kolor¢w
1.6:Uæywa ASCIIU zamiast rozszerzonego zestawu znak¢w
1.7:Wymusza uæycie strony kodowej nnn (domyòlnie wybierana automatycznie)
1.8:Opcje zaawansowane
1.9:Nadpisuje òcieæk© pomocy
1.10:jeòli nie okreòli si© æadnego pliku, uæywany jest index.htm
1.11:ùaduje inny plik niæ index.htm ze òcieæki pomocy
1.12:Gdy uæytkownik wciònie F1 lub kliknie na "pomoc o pomocy"
1.13:pomoc zaàaduje ten plik. Domyòlnie jest help.htm
1.14:Zmienne òrodowiskowe
1.15:Katalog zawieraj•cy pliki pomocy
1.16:Wpisz /M, /A, F1, F2 tutaj aby byày domyòlne

#Error Message Strings
2.0:Alokacja pami©ci niemoæliwa
2.1:Niepoprawny argument
2.2:Prosz© podaÜ tylko jeden temat
2.3:Nie moæna uæyÜ /f razem z /m
2.4:Wpisz "HELP /?" dla instrukcji uæycia.
2.5:Nie odnaleziono pasuj•cych temat¢w
2.6:Nie moæna odnale´Ü tematu
2.7:Bà•d wewn©trzny: Zmiana wielkoòci nie powiodàa si©
2.8:Nie moæna odczytaÜ skompresowanego pliku
2.9:Nie moæna otworzyÜ
2.10:Archiwum zip jest puste lub uszkodzone
2.11:Nie moæna odnale´Ü tego pliku. ùadowanie pierwszego pliku html z archiwum zip
2.12:Nie moæna odnale´Ü pliku html w archiwum zip
2.13:Podaj poprawn• stron© kodow•
2.14:Podana strona kodowa nie jest obsàugiwana
2.15:Obsàugiwane strony kodowe to

#Menu Strings
#### HTML Help will truncate strings 3.0 and 3.1
#### if they exceed 14 characters.
3.0:Wyjòcie
3.1:Pomoc o pomocy
#### HTML Help will truncate strings 3.2-3.5
#### if they exceed 10 characters.
3.2:Wstecz
3.3:Wprz¢d
3.4:ZawartoòÜ
3.5:Szukaj

#Button Label Strings
#### HTML Help will truncate strings 4.0-4.2
#### if they exceed 8 characters.
4.0:OK
4.1:Anuluj
4.2:Pomoc

#Status Bar Strings
5.0:Szukanie tematu...
5.1:Peàne wyszukiwanie w toku...
5.2:(NACIóNIJ ESC ABY PRZERWAè)...

#Search Box Strings
#### HTML Help will truncate strings:
####    6.0      if it exceeds 35 characters;
####    6.1      if it exceeds 20 characters;
####    6.2-6.5  if they exceed 28 characters;
####    6.6-6.13 if they exceed 35 characters.
6.0:Search Help
6.1:Szukany tekst:
6.2:rozr¢æniaj duæe/maàe litery
6.3:tylko peàne sàowa
6.4:peàne wyszukiwanie
6.5:na tej stronie
#Help on Search:
6.6:Do czego sàuæy
#Lines 6.7-6.9 describe "Search":
6.7:peàne wyszukiwanie:
6.8:Szuka we wszystkich plikach
6.9:wymienionych na stronie.
#Line 6.10 can be used if you need more room.
6.11:na tej stronie:
6.12:Szuka tylko i wyà•cznie
6.13:w otwartym dokumencie

#Search Results Strings
7.0:Wyniki wyszukiwania
7.1:Przeszukano wszystkie pliki wymienione na stronie
# The following line, 7.2, is used as "Searched [FILENAME]"
7.2:Szukano
# The following line, 7.3, is used as "for: [TEXT]"
7.3:dla
7.4:,Przykro mi, nie mog© przeszukiwaÜ wynik¢w.
7.5:UΩYTKOWNIK PRZERWAù (nacisn•à escape)
7.6:Brak wynik¢w
