## For instructions for translators please look into file TRANSLAT.TXT
## Changes: #m32: Cargar <BARVA=!;KLAVESY=f>f<SB>ichero INFO.TXT (double hotkey!)
## #495 replaced: C¢digos de barras by C¢digos de <BARVA=!;KLAVESY=b>b<SB>arras (double hotkey)
## m11: <BARVA=!;KLAVESY=n>N<SB>ueva archivo <<F1>>  (nuevo instead of nueva)
## m25 Seleccionar filtro de <BARVA=!;KLAVESY=i>i<SB>m†gen replaced by Seleccionar filtro de i<BARVA=!;KLAVESY=m>m<SB>†gen (double hotkey)
## m42 and m48 have double hotkey, m431 wrong hotkey f
## change primera plano in primer plano (male)
## #roz_vel_pismen: Sensitividad de casos is spanglish: <BARVA=!;KLAVESY=m>m<SB>ay£s./min£s

#identifikuj_se
Castellano (es)
#identifikuj_se2
blocek2.es
#sys_font
858-16.fv
#sys_font_maly
858-14.fv
#chyba_videomodu
El modo v°deo specificado no est† disponible:
#sys_font_kodovani
858
#m1
<BARVA=!;KLAVESY=a>A<SB>rchivo
#m2
<BARVA=!;KLAVESY=o>O<SB>pciones
#m3
A<BARVA=!;KLAVESY=y>y<SB>uda
#m31
<BARVA=!;KLAVESY=s>S<SB>obre el programa
#m32
Cargar <BARVA=!;KLAVESY=f>f<SB>ichero INFO.TXT <<ALT-F1>>
#m33
<BARVA=!;KLAVESY=i>I<SB>nformaci¢n del sistema
#m34
Ayuda <BARVA=!;KLAVESY=h>h<SB>ipertexto
#m4
<BARVA=!;KLAVESY=t>T<SB>exto
#m11
<BARVA=!;KLAVESY=n>N<SB>uevo archivo <<F1>>
#m12
<BARVA=!;KLAVESY=a>A<SB>brir    <<F3>>
#m13
<BARVA=!;KLAVESY=g>G<SB>uardar  <<F2>>
#m14
S°m<BARVA=!;KLAVESY=b>b<SB>olo de sistema
#m15
<BARVA=!;KLAVESY=s>S<SB>alir    <<ESC>>
#m16
<BARVA=!;KLAVESY=c>C<SB>errar archivo <<Alt-F3>>
#m21
<BARVA=!;KLAVESY=c>C<SB>olores
#m211
Color de <BARVA=!;KLAVESY=s>s<SB>egundo plano
#m212
Color de <BARVA=!;KLAVESY=p>p<SB>rimer plano
#m213
Color del †rea de <BARVA=!;KLAVESY=t>t<SB>rabajo
#m215
Color de l°nea <BARVA=!;KLAVESY=d>d<SB>estacado
#m22
<BARVA=!;KLAVESY=i>I<SB>dioma
#m23
Destacar <BARVA=!;KLAVESY=l>l<SB>°nea actual
#m24
Cambiar <BARVA=!;KLAVESY=f>f<SB>uente
#m25
Seleccionar filtro de i<BARVA=!;KLAVESY=m>m<SB>†gen
#m26
<BARVA=!;KLAVESY=T>T<SB>eclados preferidos
#m27
Cambiar la <BARVA=!;KLAVESY=b>b<SB>arra lateral del editor
#m28
<BARVA=!;KLAVESY=g>G<SB>uardar configuraciones
#m29
<BARVA=!;KLAVESY=e>E<SB>nfatizar los espacios
#m41
Convertir <BARVA=!;KLAVESY=p>p<SB>ara UTF-8
#m42
Convertir <BARVA=!;KLAVESY=d>d<SB>esde UTF-8
#m43
<BARVA=!;KLAVESY=a>A<SB>juste de l°nea
#m431
Corregir <BARVA=!;KLAVESY=a>a<SB>juste de l°nea actual
#m432
<BARVA=!;KLAVESY=u>U<SB>nir l°neas
#m44
Bu<BARVA=!;KLAVESY=s>s<SB>car      <<Ctrl-F>>
#m45
Buscar de <BARVA=!;KLAVESY=n>n<SB>uevo <<Ctrl-S>>
#m46
<BARVA=!;KLAVESY=r>R<SB>eemplazar      <<Ctrl-H>>
#m460
<BARVA=!;KLAVESY=m>M<SB>arcas
#m47
Mapa de carac<BARVA=!;KLAVESY=t>t<SB>eres
#m48
<BARVA=!;KLAVESY=c>C<SB>odificaciones/conversion <<CTRL-K>>
#m49
Operaciones de bloq<BARVA=!;KLAVESY=u>u<SB>e
#m490
Generar c¢digo <BARVA=!;KLAVESY=q>Q<SB>R
#m491
Car†cteres para entidades <BARVA=!;KLAVESY=h>H<SB>TML
#m492
Convertir para <BARVA=!;KLAVESY=m>m<SB>ay£scula
#m493
Convertir para m<BARVA=!;KLAVESY=i>i<SB>n£scula
#m494
Entidades HTML para <BARVA=!;KLAVESY=c>c<SB>ar†cteres
#m495
C¢digos de <BARVA=!;KLAVESY=b>b<SB>arras
#vyber_soubor
Seleccionar archivo:
#jak_to_ulozit
Escribir el nombre de archivo
#soubor_existuje_prepsat
Este archivo ya existe
®sobreescribir?
#o_programu
Sobre el programa
#napoveda
Ayuda
#varovani
<BARVA=51200>≠atenci¢n!<SB>
#opravdu_konec
®Realmente salir?
Los modificaciones no ser†n guardados.
#tento_soubor_uz_jednou_mame
Este archivo ya est† abierto.
Blocek te permite abrirlo de nuevo, ≠pero se
comportar† de forma independiente de la instancia anterior!
(NO COMO EL IDE F.E. PASCAL)
#unicode
unicode
#zalamovani
ajuste de l°nea
#proporcionalni_mod
proporcional
#vyber_barvu_popredi
Seleccionar color de segundo plano
#vyber_barvu_pozadi
seleccionar color de primera plano
#vyber_barvu_zakladu
seleccionar color del †rea de trabajo
#vyber_barvu_prosv
Elige color
#zda_pro_rad
®Deseas resaltar la l°nea actual?
#nastaveni_ulozeno
Configuraciones guardados
#zatim_neni
Esta funci¢n a£n no est† disponible.
#hypertextova_napoveda
Sistema del ay£da hipertexto

#napoveda_koren
Blocek - editor de texto y visor de im†genes

T¢picos de ayuda:
1) <OK="napoveda_klavesy">Controlar con el teclado<OK/>
2) <OK="napoveda_mys">Controlar con la rat¢n<OK/>
3) <OK="napoveda_prvky">Elementos de controles<OK/>

#napoveda_klavesy
<FONT=surea37.fn;barva=65346>Controlar con el teclado<SB;SF>
<barva=65535>F10<sb>   - entrar la men£ principal
<barva=65535>F1<sb>    - criar una nuevo archivo
<barva=65535>F2<sb>    - guardar archivo
<barva=65535>F3<sb>    - cargar archivo
<barva=65535>Alt+F3<sb> - cerrar archivo
<barva=65535>Alt+F1<sb> - cargar este archivo (INFO.TXT)
<barva=65535>Ctrl+F<sb> - buscar
<barva=65535>Ctrl+S<sb> - buscar de nuevo
<barva=65535>Ctrl+H<sb> - reemplazar
<barva=65535>Ctrl+A<sb> - seleccionar todo el documento desde la bloque
<barva=65535>Ctrl+Q<sb> - ofrecir una variante para la £ltima car†cter escrito (c¢mo a-†-É-...])
<barva=65535>Ctrl+K<sb> - funcionalidades del conversi¢n de car†cteres
<barva=65535>Ctrl+L<sb> - llamada r†pida de la edici¢n de l°neas
<barva=65535>LShift+Alt<sb> - cambiar la disposici¢n de teclado
<barva=65535>Ctrl+Alt+Arriba<sb> - seleccionar l°nea actual para bloque
<barva=65535>Ctrl+Alt+Abajo<sb> - palabra en el cursor para bloque
<barva=65535>Ctrl+Alt+Izquierda<sb> - todos los car†cteres desde cursor para izquierda para bloque
<barva=65535>Ctrl+Alt+Derecho<sb> - todos los car†cteres desde cursor para derecho para bloque
<barva=65535>Backspace<sb> - borrar un car†cter izquierda para cursor
<barva=65535>Canc<sb> - borrar un car†cter derecho para cursor
<barva=65535>May£s+Canc<sb> - borrar la bloque seleccionado
<barva=65535>*flechas<sb> - movimientos del cursor
<barva=65535>*Ctrl+AvP†g<sb> o <barva=65535>*Ctrl+Home<sb> - saltar en primera l°nea del archivo
<barva=65535>*Ctrl+PageDown<sb> o <barva=65535>*Ctrl+Fin<sb> - saltar en £ltima l°nea del archivo
<barva=65535>*Ctrl+DerechaArrow<sb> - mueve una palabra a la derecha
<barva=65535>*Ctrl+IzquierdaArrow<sb> - mueve una palabra a la izquierda
   Estas teclas de funci¢n (marcadas con "*") se pueden combinar con <barva=65535><May£s><sb>.
   En tal caso, con el movimiento del cursor tambiÇn puedes crear o actualizar
   el bloque de selecci¢n de texto.
<barva=65535>Ctrl+[1-7]<sb> - copiar bloque seleccionada de texto para portapapeles nß 1-7
<barva=65535>Alt+[1-7]<sb> - pegar texto desde portapapeles nß 1-7 para la posici¢n del cursor
<barva=65535>Ctrl+m†s<sb> y <barva=65535>Ctrl+minus<sb> (en el teclado numÇrico) - cambio r†pido entre los archivos abiertos hacia adelante o hacia atr†s
<barva=65535>ESC<sb>   - salir
<barva=65535>Alt+F2<sb> - criar una captura de pantalla

#napoveda_mys
<FONT=surea37.fn;barva=65346>Controlar con la rat¢n<SB;SF>
<barva=65535>1) En el ventana del documento<SB>
Clic con el bot¢n de rat¢n izquierda (LMB) - mueve el cursor al lugar seleccionado en el texto
LMB clic+shift - selecciona el inicio y el final del bloque de texto
LMB pulsa y arrastrar - selecci¢n inter†ctivo de bloco de texto
Clic con el bot¢n de rat¢n derecho (RMB) - muestra informaci¢n y opcionalmente un men£ de conversi¢n para el car†cter en el que hiciste clic.
TambiÇn accessar los funciones para trabajar con marcas.

<barva=65535>2) En el panel con archivos abiertos<SB>
LMB clic - cambia la ventana principal al archivo especificado
RMB clic - diversas funcionalidades con la archivo specificado
(cerrar, cerrar todo excepto este, mostrar la ruta completa del archivo)

<barva=65535>3) En los indicadores de portapapeles<SB>
LMB clic - men£ para los operaciones con los portapapeles

<barva=65535>4) Otras precauciones<SB>
->> Todos los dem†s botones y elementos de la GUI solo usan el bot¢n izquierdo del
    rat¢n en este momento. El bot¢n derecho no se usa actualmente.
->> Casi todas las ventanas de di†logo se pueden mover en la pantalla arrastrando su barra de t°tulo.
->> Arrastrar con el rat¢n (el bot¢n izquierdo) sobre el texto en las ventanas de informaci¢n (incluida esta)
    puede seleccionar el bloque de texte para copiar en el portapapeles utilizando Ctrl+[1-7] para pegar
    posteriormente una ventana de documento.

#napoveda_prvky
<FONT=surea37.fn;barva=65346>Elementos de controles<SB;SF>
La mayor parte del espacio de trabajo est† cubierta por la <barva=65535>ventana principal<SB>. En esta ventana se muestra un documento con texto editable o el visor con una imagen cargada.
En el lado izquierdo de la ventana del editor puede haber un panel opcional que contiene indicadores que muestran c¢mo se terminan las l°neas individuales del documento.
Por encima de este espacio hay tres paneles horizontales.

<barva=65535>1) Panel permanente<SB>
El men£ principal con los elementos: <barva=65535>Archivo<SB>, <barva=65535>Texto<SB>, <barva=65535>Opciones<SB>, <barva=65535>Ay£da<SB>
A la derecha de estos elementos se encuentran los <OK="napoveda_indikatory">indicadores del portapapeles</OK> para los bloques del texto numerados del 1 al 7.
A£n m†s a la derecha (en la esquina superior derecha) hay una lista desplegable, en la cual se puede elegir la disposici¢n del teclado.
Esta lista tambiÇn se puede abrir con el atajo de teclado <OK="napoveda_klavesy">ALT+SHIFT<OK/>

<barva=65535>2) Panel de contexto<SB>
Carga el funci¢n del contenido de la ventana principal.
Si se muestra una imagen, entonces en la parte izquierda se muestra su di†metro en p°xeles. A la derecha de esto se encuentran los botones para pantalla completa, para el tama§o de ventana ¢ptimo y para la rotaci¢n y volteo 
de la imagen.
Si se muestra un documento editable, entonces el panel contextual es diferente. En el lado izquierdo hay un bot¢n que enlaza a una ventana de di†logos para diversas funcionalidades de conversi¢n de p†gina de c¢digo. 
(tambiÇn se puede activar con la tecla <OK="napoveda_klavesy">CTRL+K<OK/>).
Al lado derecho se encuentra el bot¢n para establecer las opciones de ajuste de l°nea.
A la derecha de este bot¢n hay una casilla de verificaci¢n que alterna entre los modos de ajuste de l°nea. Hacia el borde derecho se muestra la posici¢n actual del cursor.

<barva=65535>3) Panel con cajas de archivos abiertos<SB>
Hasta que un archivo estÇ cargado, el tercer panel est† vac°o. Cuando se abre un archivo, su mapa se muestra en este panel. En el editor Blocek es posible tener varios archivos abiertos simult†neamente.
Sus mapas se muestran uno al lado del otro y el usuario puede alternar entre ellos con el <OK="napoveda_mys">rat¢n<OK/>.
El bot¢n izquierdo del rat¢n alterna la ventana principal hacia el archivo especificado (documento o imagen). El bot¢n derecho del rat¢n abre un submen£ que permite cerrar el archivo, cerrar todos los dem†s archivos y 
acceder a la funci¢n que permite mostrar la ruta completa del archivo.

#napoveda_indikatory
Si se copia texto en el portapapeles (con la combinaci¢n <OK="napoveda_klavesy">CTRL+[1-7]<OK/>) o con el bot¢n especial en varias ventanas de di†logo, entonces la presencia en un portapapeles dado se indica.
Su indicador cambia la color a blanco y parece una bombilla encedida.
Si el portapapeles est† vac°o, entonces la visualizaci¢n es en negro con el s°mbolo de un c°rculo tachado.
El indicador del portapapeles n£mero 7 puede mostrarse como <BARVA=65535>7W<SB>. Esto significa que los servicios de portapapeles del sistema MS Windows (o una interfaz compatible) est†n disponibles. En este caso, el 
portapapeles n£mero 7 est† vinculado al portapapeles de MS Windows y es posible intercambiar bloques de texto de otros programas. M†s detalles sobre el archivo TECHNOTE.TXT.<SB>

#text_napovedy
<FONT=surea37.fn>Blocek<SF>
versi¢n 1.77b
Fecha de compilaci¢n: <BARVA=65535>28.9.2026<SB>
programado por Laaca (laaca@seznam.cz)

Blocek es un editor de texto y visor de im†genes
que es capaz de editar archivos con codificaci¢n Unicode
UTF-8, por lo que es muy pr†ctico para escribir p†ginas WWW.
Blocek puede editar archivos muy grandes y l°neas muy largas.
Gracias a Mateusz Viste por sus fuentes Unicode.
Blocek tambiÇn se puede usar como un visor simple de archivos
en los formatos gr†ficos comunes. Sin embargo, no es capaz
de editar im†genes

Este programa es publicado como software libre y c¢digo abierto
en la licencia GNU/GPL<SF>


#parametr_otaznik
Sintaxo:
BLOCEK [archivo1 [,archivo2 [,...]]]
#ovladani_obrazku
ventana ¢ptimo*o<<>>O*+90*-90*horiz*vert*datos Exif

#soubor_nebyl_ulozen
≠El archivo no fueron guardado!
no hay suficiente espacio en el unidad o
la unidad es de solo lectura


#chyba_font_int
Se produjo un error al cargar el archivo de fuente
#chyba_font_neint
Falta el archivo de fuente o se produjo un error al cargarlo:

#informace_exif
Informaci¢n Exif
#exif_date_strs
Fecha y hora:          *Fecha y hora del original:*Fecha y hora del tiro al c†mara:
#exif_camera_info
Fabricante:*Modelo:*Descripci¢n:*Software:*Fuente de luminaci¢n:*Brillo:*Modo de exposura:*ISO:*Tiempo de exposura:*Orientaci¢n:*Zoom:
#exif_lightsrc_info
Desconocido*Luz del d°a*Fluorescente*Tungsten*Brillo*Luminaci¢n est†ndar A*Luminaci¢n est†ndar B*Luminaci¢n est†ndar C*D55*D65*D75*Otro*Desconocido
#exif_flash_info
Ning£na brillo*Brillo*Brillo sin pre-destello*Brillo destello*Brillo (auto)*Ning£na brillo*Desconocido
#exif_expos_mode
Desconocido*Control manual*Programa normal*Prioridad apertura*Shutter Priority*Programa creativo*Programa acci¢n*Portrait Mode*Landscape Mode*Desconocido
#exif_orientation_desc
Normal*Espejado horiz.*Girado 180*Espejado vert*Girado 90 a la izquierda y reflejado*Girado 90 a la izquierda*Girado 90 a la derecho y espejado*Girado 90 a la derecho*Desconocido
#exif_zoom_unused
No utilizado
#exif_GPS_info
Informaci¢n GPS*latitud:*longitud:*altitud:*azimut*N*S*W*E*m*metros*grados*minutos*segundos
#zkopirovat_exif
Desde portapapeles
#nejde_o_obrazek
El archivo est† da§ado o los datos del im†gen
es un formato soportado
El archivo ser†n abierto como texto.
#nelze_fixovat_zalamani
Esta funci¢n est† disponible
s¢lo en el modo ajuste de l°nea
#vyhledavani
Buscar
#rezim_vyhled
<POZADI=1147;BARVA=65535>modo de b£squeda<POZADI=->
#vyhled_mozn
<BARVA=!;KLAVESY=d>d<SB>desde cursor
<BARVA=!;KLAVESY=p>p<SB>ara cursor
desde el <BARVA=!;KLAVESY=i>i<SB>nicio
#roz_vel_pismen
Distinguir <BARVA=!;KLAVESY=m>m<SB>ay£s./min£s
#text_nenalezen
La texto seleccionado no fueron encontrado.
#nahradit_vyskyt
®Reemplazar esta occurencia?
#potvrzovat
c<BARVA=!;KLAVESY=o>o<SB>nfirmaci¢n
#nahradvse
reemplazar <BARVA=!;KLAVESY=t>t<SB>odos
#hledany_text
Texto para buscar
#novy_text
Nuevo texto
#nahrada_textu
Reemplazar
#vyber_filtr
Seleccionar filtro de conversi¢n
#opravdu_zavrit
El archivo fueron modificado.
®Guardarlo?
#zavrit_ostatni
Cerrar todo excepto este
#umisteni_souboru
Ubicaci¢n del archivo
#bezejmenny
<BARVA=46815><<nuevo archivo>><SB>
#bezejmenny_soubor
Nuevo archivo

#zrusit_nac
®Anular la carga?
#chybi_bcfg
El archivo <BARVA=65535>BLOCEK.CFG<SB> no se encuentra.
Ser†n criado desde el archivo por defecto
<BARVA=65535>DEFAULT.CFG<SB>
#chybny_bcfg
El archivo <BARVA=65535>BLOCEK.CFG<SB> es invalido.
Voy a crearlo desde el archivo
<BARVA=65535>DEFAULT.CFG<SB>
#pridani_bcfg
Los variables fueron a§adidos para la archivo <BARVA=65535>BLOCEK.CFG<SB>:
#pocet_zmen
Encontrado*N£mero de modificaciones:*N£mero de occurencias:*Modo de contar <BARVA=!;KLAVESY=c>c<SB>adenas occurencias
#neniswap
≠Tu sistema no es compatible con la memor°a virtual!
Puede ser peligroso en situaciones cuando todas las RAM est†s consumidos.
Por favor, usa otro gestor DPMI.
est†s actualmente utilizando:
#dpmineznamy
<BARVA=333>gestor DPMI desconocido :-(<SB>
#kaslinaswap
(Puede deshabilitar esta verificaci¢n en BLOCEK.CFG ajustando
<BARVA=65530>zkontroluj_swap = 0<SB>)
#plnyseznam
Lista completa...
#vybprefkl
®Cuales teclados deber°an aparecer en la men£ principal?
#vybprefflt
®Cuales filtros deber°an aparecer en la men£ principal?

#asciiauto
detecci¢n autom†tico

#vkod
<PODTRH=+>origen<PODTRH=->
#ckod
<PODTRH=+>destino<PODTRH=->
#oznaceno
seleccionado:
#ozn_nic
ninguna
#kompinfo
Procesador:*Memoria:*Mb RAM*V°deo:Versi¢n VESA:Modo v°deo:*Memoria v°deo*Frecuencia de refrescante:*BIOS por defecto*Versi¢n DOS:*Ampliaci¢n de car†cteres:*Identificaci¢n de pa°s DOS:*OS
#videomody
Modos de <BARVA=!;KLAVESY=v>v<SB>°deo*Lista de modos de v°deo
#kompinfo_lfn
Nombres de archivos largas (LFN):
#schranka_c
Portapapeles n.ß
#schranka_do
Copiar para portapapeles
#schranka_ze
Pegar para cortapapeles
#schranka_copy
Copiar para otro cortapapeles
#smaz
Eliminar
#vyber_jazyk
Seleccionar tu idioma
#nutny_restart
Debes reiniciar la programa para el cambia por hacer efecto.
#prevod_html_entity
Conversi¢n para entidades HTML
#prevod_html_ent_info
Los car†cteres con un valor ASCII o Unicode superior al 127
ser†n convertidos para entidades HTML.
La deseo del conversi¢n est† definidos por la bloque.
#text_je_v_unicod
El texto est†n en Unicode.
#text_je_v_ascii
El texto est†n en ASCII y la conversi¢n
ser† utilizados con la tabla de conversi¢n.
#neni_oz_blok
Ning£na bloque de texto est† seleccionado, pues la conversi¢n
ser† pasado a travÇs de todo el texto.
#prevod_mala_velka
Convertir para may£sculas
#prevod_mala_velka_inf
Convertir la bloque para may£sculas.
No tocar los otros car†cteres.
#prevod_velka_mala
Convertir para min£sculas
#prevod_velka_mala_inf
Convertir la bloque para may£sculas.
No tocar los otros car†cteres.
#kodovani_dokumentu
Codificaci¢n:
#help_non_unicode
Solo cambia la etiqueta del juego de caracteres. No cambia la fuente.
#help_inter_znaku
Conversi¢n entre car†cteres simples y secuencias de m£ltiples car†cteres en UTF-8 o UTF-16.
Algunos subfuncionalidades tambiÇn est†n aplicados al bloques de texto y algunos s¢lo para otros
y la documento total.
En cambiar entre Unicode y no Unicode o vice-versa, la fuente ser† modificado.

#help_tabkonv_znaku
Recodificar las car†cteres con los tablas de conversi¢n. El n£mero de car†cteres permanecer† identico.
Puede ser aplicado a todo el documento o s¢lo para la bloque specificado.
En cambiar entre Unicode y no Unicode o vice-versa, la fuente ser† modificado.

#analyza_nedef_zn_dok
Analiza del car†cteres no definidos en todo el texto

#analyza_nedef_zn_blok
Analiza del car†cteres no definidos en la bloque definido

#poc_vysk_nedef_znaku_n
n£mero de occurencias de car†cter

#poc_vysk_nedef_znaku_vse
n£mero de todos los car†cteres indefinidos

#poc_vysk_nedef_znaku_unik
n£mero de car†cteres indefinidos £nicos*alcance

#zamena_znaku
®Cambiar para otro car†cter?

#nedefinovany_znak
Car†cter indefinido*An†lisis caracteres indefinidos (bloque/texto)

#nedefinovany_znak_zam
®Reemplazar todos los car†cters indefinidos?

#zamena_znak_radiob1
S¢lo esta vez
En el documento total
En la bloque seleccionado

#zamena_znak_radiob2
Todas partes
Desde inicio para caracter marcado
Desde la caracter marcado

#znak_k_zamene
Reemplazar car†cter...

#dotaz_pri_zmene
®Preguntar durante la cambiamento?

#kodovaniascii_dlg
Codificaci¢n ASCII probable:*imposible de determinar*®Est†s de acuerdo?

#polozka_dos
(usar una tabla)*(sin tabla)*m†s...

#tbl_filtr_ascii
Conversi¢n en grupo:*codificaci¢n origen*codificaci¢n destino

#niz_nonunicode1
®La texto muestrado usar este codificaci¢n?

#niz_nonunicode2
La codificaci¢n origen y destino son idÇnticas.
Ning£na cambios ser†n efectuados.

#ascii_2_utf_1
Conversiones entre ASCII y secuencias m£lti-octos UTF-8 o UTF-16

#ascii_2_utf_2
Operaciones de bloques (no cambia la marcador de codificaci¢n)

#ascii_2_utf_3
Operaciones en la documento total (la marcador de codificaci¢n cambiar a no Unicode)

#uni_2_utf_1
Conversiones entre Unicode y secuencias m£lti-octos UTF-8 o UTF-16

#uni_2_utf_2
Operaciones de bloques (no cambia la marcador de codificaci¢n)

#uni_2_utf_3
Operaciones en la documento total (la marcador de codificaci¢n cambiar a no Unicode [DOS])

#uni_2_utf_4
Unicode --> UTF-8 (representado como car†cteres ASCII en DOS)

#prohozeni_endianity
Cambia la bautismo de car†cteres Unicode

#tab_konv_zn
Hace ning£na conversiones. S¢lo cambia la marcador de codificaci¢n para no Unicode (DOS ASCII)
Los car†cteres en el alcance 0-255 no cambian y los car†cteres bajo 255 se reemplazan por un espacio reservado.

#zda_prenastavit_font_1
®TambiÇn cambiar la fuente y marcador de codificaci¢n para la configuraci¢n no Unicode?

#zda_prenastavit_font_2
®TambiÇn cambiar la fuente y marcador de codificaci¢n para la configuraci¢n Unicode?

#pren_font_ano
(la conversi¢n de texto completo, as° probablemente S÷)

#pren_font_ne
(la conversi¢n limitado al bloque de texto, as° probablemente NO)

#preznacit_kodovani
®Debo actualizar la marcador de codificaci¢n de documento?

#zm_kod_dok
Cambiamento de la codificaci¢n de documento

#zak_unicode
La documento est† codificado en Unicode.

#sada_a_filtr_souborem
El juego de car†cteres y filtro de conversi¢n para Unicode est†n specificados en el archivo:

#interp_nonuni
Interpretaci¢n no Unicode

#konv_zn_utf
Conversi¢n de car†cteres/secuencias UTF

#tab_konv_zz
Conversi¢n de car†cteres/car†cteres basados en tablas

#zmena_fontu
Cambiar fuente

#nas_zal_rad
Opciones del salto de l°nea

#nas_zal_mozn
por la pesta§a de documento
78 car†cteres
80 car†cteres
otros...

#filesel_nejde_konverze
La nombre de archivo entrada no puede ser convertido para la p†gina de c¢digo DOS actual.
®Continuar de todas formas?

#podrobnosti
Detalles

#moznosti...
Opciones...

#form_konc_rad
Formato de fin de l°nea

#form_konc_help
Recomienda a dejar la est†ndar CRLF que es com£n en las sistemas
DOS o Windows.
LF es est†ndar para Unix/Linux y
CR se usaba por los ordenadores Macintosh.

#form_konc_mozn
CRLF (DOS/win)
LF (Unix)
CR (Mac)

#b_ord_mark
Byte order mark (BOM)

#bom_help
"BOM" = "byte order mark"
S¢lo aplicar a los archivos en Unicode.
Es una secuencia de dos o tres octos al muy inicio del archivo.
Es recomendado a usar BOM por los archivos en UTF-16.
En los documentos UTF-8, se usar rareamente.

#bom_mozn
UTF-8
UTF-16le
UTF-16be

#opravdu_fix_lom
®Realmente corrigir la saltar de l°nea en el documento total?

#rozs_fix_lom_blok
El bloque no contiene alg£n fin de l°nea.
®Debo extender y continuar?

#jen_nezalam_rezim
Esta funci¢n solo est† disponible para el modo ajuste de l°nea.

#opravdu_spoj_radky
®Realmente aplicar el alg¢ritmo de unir l°neas en el documento total?

#nahr_faze
1¶ fase:*2¶ fase:*3¶ fase:

#jen_v_bloku
<BARVA=!;KLAVESY=S>S<SB>¢lo en el bloque

#prevod_z_html_entit
Decodificar los entidades HTML para los car†cteres

#prevod_z_html_entit_info
Identificar los entidades HTML en el formato n£merico (como &#8222;) y reemplazar con los car†cteres Unicode

#qr_vygenerovany
C¢digo QR generado

#qr_ulozit
Guardar

#qr_velikost
Tama§o de punto de c¢digo QR (1-20)

#qr_uspech
≠Succeso! Guardado con nombre de archivo:

#qr_chyba
Error durante conversi¢n para el c¢digo QR.

#qr_chyba_save
Error durante guardar para el c¢digo QR.

#qr_tvorba
Creaci¢n de c¢digos QR

#qr_text
Texto para crear el c¢digo QR

#related_characters
Car†cteres relacionados

#zalozky
Marcadores*Marcador nß*Mostrar marcadores

#menu_slovo
Men£/Palabra

#dialogy_menu_slovo
Di†logo buscar*Di†logo reemplazar*MAYÈSCULAS*min£sculas*Capitalizar*Al portapapeles

#menu_radek
Men£/L°nea

#dialogy_menu_radek1
L°nea a bloque:
C<BARVA=!;KLAVESY=o>o<SB>n ajuste de l°nea
Si<BARVA=!;KLAVESY=n>n<SB> ajuste de l°nea

#dialogy_menu_radek2
Espacios:
Quitar los espacios <BARVA=!;KLAVESY=i>i<SB>nicios
Quitar los espacios <BARVA=!;KLAVESY=f>f<SB>inales

#dialogy_menu_radek3
Indentaci¢n del l°neas:
de acordo en la l°nea <BARVA=!;KLAVESY=p>p<SB>recedente
de acordo en el <BARVA=!;KLAVESY=t>t<SB>abulador

#dialogy_menu_radek4
m†s 1 * menos 1 * m†s 4 * menos 4

#pmysmenu
<BARVA=!;KLAVESY=c>c<SB>ar†cter
<BARVA=!;KLAVESY=p>p<SB>alabra
<BARVA=!;KLAVESY=l>l<SB>°nea

#doprad
Expansi¢n de l°neas

#doprad_txt
Escribe uno o m†s car†cteres que
ser†n usados para expandir la l°nea
por la fin o la inicio.

Por defecto es [espacio]

#zarovnani
Al°neamento:*para izquierda*para derecho

#carkod_tvorba
C¢digos de barras

#carkod_instr
Entrar una texto corto o n£mero
Aviso: Algunos estandares de c¢digos de barras s¢lo codificar† los n£meros.
TambiÇn no preocupe que algunos c¢digos de barras (como EAN-13) muestra los
c¢digos validos con los sumas de controles correctos. Los valores inv†lidos puede
codificarse, pero es posible que la c¢digo de barra no ser† valido por al aplicaci¢n de lector.

#carkod_ulozit
Guardar

#carkod_uspech
≠êxito! Guardado con nombre de archivo:

#carkod_chyba
Error durante la conversi¢n para el c¢digo barra.

#carkod_chyba_save
Error durante la guardar para el c¢digo barra.

#carkod_combine
Combinar con cadena codificada

#carkod_mozn
Este cadena puede ser codificados para estos c¢digos barras:
